name: Release

on:
  # Run the workflow each time new commits are pushed to the candidate branch. 
  push:
    branches: [ "candidate" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  actions: read

jobs:
  get-architectures:
    name: ðŸ–¥ Get snap architectures
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.get-architectures.outputs.architectures }}
      architectures-list: ${{ steps.get-architectures.outputs.architectures-list }}
    steps:
      - name: ðŸ–¥ Get snap architectures
        id: get-architectures
        uses: jnsgruk/snapcrafters-ci/get-architectures@initial-build

  release:
    name: ðŸš¢ Release to latest/candidate
    needs: get-architectures
    runs-on: ubuntu-latest
    environment: "Candidate Branch"
    strategy:
      matrix:
        architecture: ${{ fromJSON(needs.get-architectures.outputs.architectures-list) }}
    steps:
      - name: ðŸš¢ Release to latest/candidate
        uses: jnsgruk/snapcrafters-ci/release-to-candidate@initial-build
        with:
          architecture: ${{ matrix.architecture }}
          launchpad-token: ${{ secrets.LP_BUILD_SECRET }}
          store-token: ${{ secrets.SNAP_STORE_CANDIDATE }}

  call-for-testing:
    name: ðŸ“£ Create call for testing
    needs: [release, get-architectures]
    environment: "Candidate Branch"
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.issue.outputs.issue-number }}
    steps:
      - name: ðŸ“£ Create call for testing
        id: issue
        uses: jnsgruk/snapcrafters-ci/call-for-testing@initial-build
        with:
          architectures: ${{ needs.get-architectures.outputs.architectures }}
          ci-repo: "jnsgruk/snapcrafters-ci"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          store-token: ${{ secrets.SNAP_STORE_CANDIDATE }}
